name: "Build"
on:
  pull_request:
  push:
jobs:
  probe-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: probe-run-win
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix --log-format bar-with-logs build .#probe-run
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: probe-run.exe
        path: result/bin/probe-run.exe
        retention-days: 90

  probe-rs-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: probe-run-win
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix --log-format bar-with-logs build .#probe-rs-cli
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: probe-rs-cli.exe
        path: result/bin/probe-rs-cli.exe
        retention-days: 90
